version: '3'
services:
  wordpress:
    build: 
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    # image: docker.io/aprilsea/wordpress
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: wp_user
      DB_PASSWORD: wp_pass
      DB_NAME: wordpress
      WP_DEBUG: "true"
      WP_ADMIN: "true"
      MULTISITE: "false"
      WP_SITEURL: http://localhost:8080/
      WP_HOME: http://localhost:8080/
    command: sleep infinity
    links:
      - db
    volumes:
      - ../:/app
 
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql