version: '3'
services:
  wordpress:
    build: 
      context: ../
      dockerfile: ./.docker/Dockerfile  
    image: docker.io/aprilsea/chang-ai:wordpress.xdebug 
    ports:
      - 8080:80
    environment:
      # DB_HOST: s3.topdev.app:17297
      DB_HOST: db
      DB_USER: avnadmin
      DB_PASSWORD: 
      DB_NAME: wordpress
      WP_DEBUG: "true"
      WP_ADMIN: "true"
      MULTISITE: "false"
      WP_SITEURL: http://localhost:8080
      WP_HOME: http://localhost:8080
    links:
      - db
    volumes:
      - ../:/app
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: avnadmin
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql